# Deploy manually

name: Test Variable handling

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-installer:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set Variable
        run: |
          $BuildTime = Get-Date -format yyyymmddHHmmss
          $BuildBranch = "master"
          $BuildId = "$BuildTime-$BuildBranch" 
          echo '${env:GIHUB_ENV}'=${env:GITHUB_ENV}
          echo "build_id=$BuildId"
          echo "build_id=$BuildId" >> ${env:GITHUB_ENV}
        shell: powershell

      - name: Use variable
        run: |
          echo env.build_id=${{ env.build_id }}
          echo `$build_id=$build_id
          echo '${env:build_id}'=${env:build_id}
        shell: powershell
